
package mil.nga.gdp.services;

import javax.jws.WebService;
import javax.xml.ws.BindingType;

import mil.nga.gdp.core.GetProducts;
import mil.nga.gdp.core.GetProductsBBOXmessage;
import mil.nga.gdp.core.GetProductsWKTmessage;
import mil.nga.gdp.core.GetProductsUnitNamemessage;
import mil.nga.gdp.core.GetProductsCNTRYmessage;
import mil.nga.gdp.core.GetProductsAORJMPmessage;
import mil.nga.gdp.core.RequestResponse;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(
    portName = "getProductsServicePort", 
    serviceName = "get_products_service", 
    targetNamespace = "mil:nga:getProducts", 
    wsdlLocation = "file:/export/home/carpenlc/java/getProductsService/src/main/resources/wsdl/getProductsService.wsdl", 
    endpointInterface = "mil.nga.gdp.GetProducts")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class getProductsServiceWSImpl
    implements GetProducts
{


    public getProductsServiceWSImpl() {
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.nga.gdp.RequestResponse
     */
    public RequestResponse getProductsBbox(GetProductsBBOXmessage parameters) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.nga.gdp.RequestResponse
     */
    public RequestResponse getProductsWkt(GetProductsWKTmessage parameters) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.nga.gdp.RequestResponse
     */
    public RequestResponse getProductsUnit(GetProductsUnitNamemessage parameters) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.nga.gdp.RequestResponse
     */
    public RequestResponse getProductsCNTRY(GetProductsCNTRYmessage parameters) {
        //replace with your impl here
        return null;
    }

    /**
     * 
     * @param parameters
     * @return
     *     returns mil.nga.gdp.RequestResponse
     */
    public RequestResponse getProductsAorJmp(GetProductsAORJMPmessage parameters) {
        //replace with your impl here
        return null;
    }

}
