
package mil.nga.gdp.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "get_products_service", targetNamespace = "mil:nga:getProducts", wsdlLocation = "file:/export/home/carpenlc/java/getProductsService/src/main/resources/wsdl/getProductsService.wsdl")
public class GetProductsService
    extends Service
{

    private final static URL GETPRODUCTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETPRODUCTSSERVICE_EXCEPTION;
    private final static QName GETPRODUCTSSERVICE_QNAME = new QName("mil:nga:getProducts", "get_products_service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/export/home/carpenlc/java/getProductsService/src/main/resources/wsdl/getProductsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETPRODUCTSSERVICE_WSDL_LOCATION = url;
        GETPRODUCTSSERVICE_EXCEPTION = e;
    }

    public GetProductsService() {
        super(__getWsdlLocation(), GETPRODUCTSSERVICE_QNAME);
    }

    public GetProductsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETPRODUCTSSERVICE_QNAME, features);
    }

    public GetProductsService(URL wsdlLocation) {
        super(wsdlLocation, GETPRODUCTSSERVICE_QNAME);
    }

    public GetProductsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETPRODUCTSSERVICE_QNAME, features);
    }

    public GetProductsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetProductsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetProducts
     */
    @WebEndpoint(name = "getProductsServicePort")
    public GetProducts getGetProductsServicePort() {
        return super.getPort(new QName("mil:nga:getProducts", "getProductsServicePort"), GetProducts.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetProducts
     */
    @WebEndpoint(name = "getProductsServicePort")
    public GetProducts getGetProductsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("mil:nga:getProducts", "getProductsServicePort"), GetProducts.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETPRODUCTSSERVICE_EXCEPTION!= null) {
            throw GETPRODUCTSSERVICE_EXCEPTION;
        }
        return GETPRODUCTSSERVICE_WSDL_LOCATION;
    }

}
