package mil.nga.gdp.types;

import java.io.Serializable;

/**
 * This class is a POJO implementation of bounding box.  This class has the 
 * same method signatures as the BBOX class which was generated by Axis2 from
 * the <code>get_products_service.wsdl</code> WSDL.  The difference is that 
 * this class does not contain the SOAP plumbing and can be utilized without
 * Axis2.
 * 
 * @author L. Craig Carpenter
 */
public class BoundingBox implements Serializable {

    /**
	 * Eclipse-generated serialVersionUID
	 */
	private static final long serialVersionUID = 4018182276390793377L;
	
	/**
     * Internal member variables
     */
    protected double upperRightLon = 0.0;
    protected double lowerLeftLat  = 0.0;
    protected double lowerLeftLon  = 0.0;
    protected double upperRightLat = 0.0;
    
    /**
     * Getter method for the lower left latitude
     * @return double
     */
    public double getLowerLeftLat(){
        return lowerLeftLat;
    }
    
    /**
     * Getter method for the lower left longitude
     * @return double
     */
    public double getLowerLeftLon(){
        return lowerLeftLon;
    }
     
    /**
     * Getter method for the upper right latitude.
     * @return double
     */
    public double getUpperRightLat(){
        return upperRightLat;
    }
    
    /**
     * Getter method for the upper right longitude.
     * @return double
     */
    public double getUpperRightLon(){
        return upperRightLon;
    }
    
    /**
     * Setter method for the lower left latitude
     * @param value lower left latitude
     */
    public void setLowerLeftLat(double value){
        lowerLeftLat=value;
    }
         
    /**
     * Setter method for the lower left longitude
     * @param value lower left longitude
     */
    public void setLowerLeftLon(double value){     
        lowerLeftLon=value;
    }

    /**
     * Setter method for the upper right latitude.
     * @param value Upper right latitude.
     */
    public void setUpperRightLat(double value){
        upperRightLat=value;
    }

    /**
     * Setter method for the upper right longitude
     * @param value Upper right longitude
     */
    public void setUpperRightLon(double value){ 
        upperRightLon=value;            
    }

    /**
     * Convert to human readable String.
     */
    public String toString() {
    	StringBuilder sb = new StringBuilder();
    	sb.append("Bounding box: Lower left latitude => [ ");
    	sb.append(Double.toString(getLowerLeftLat()));
    	sb.append(" ], lower left longitude => [ ");
    	sb.append(Double.toString(getLowerLeftLon()));
    	sb.append(" ], upper right latitude => [ ");
    	sb.append(Double.toString(getUpperRightLat()));
    	sb.append(" ], upper right longitude => [ ");
    	sb.append(Double.toString(getUpperRightLon()));
    	sb.append(" ].");
    	return sb.toString();
    }
}
